### ISSUE TITLE
Move the reproducible codes into a new repo

### ISSUE THREAD

**Issue by beyondpie** [JunLiuLab/SIMPLEs#4]
@xyz111131 

We need to keep SIMPLEs clear, and it should be an R package with demos or tutorials. Other codes (the reproducible ones for the paper) might be put into a new repo specific for its aim.

I will move those codes today if you think it's not bad.

**Comment by xyz111131** [comment]
Yes, it's better to separate them.

**Comment by beyondpie** [comment]
I use SIMPLEs2020 repo now.
